'use client';
import {motion} from 'framer-motion'; import {ArrowUpRight,Download,Mail,Code2,Database,Server,BrainCircuit} from 'lucide-react'; import {projects,skills} from '../data/portfolio';
const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.55}};
export default function Portfolio(){return <main>
<nav><a className="brand" href="#top">UF<span>.</span></a><div className="navlinks"><a href="#about">About</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a href="#contact">Contact</a></div><a className="resume small" href="/Umar_Farooque_Resume.pdf" download><Download size={15}/> Resume</a></nav>
<section id="top" className="hero"><div className="orb one"/><div className="orb two"/><motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="heroInner"><p className="eyebrow">SOFTWARE DEVELOPER · BACKEND · SYSTEMS · AI/ML</p><h1>I build software that<br/><span>works beyond the demo.</span></h1><p className="lead">Computer Science student building scalable backend systems, production-oriented applications and practical machine-learning products.</p><div className="actions"><a className="primary" href="#projects">Explore my work <ArrowUpRight size={17}/></a><a className="secondary" href="mailto:umar80643@gmail.com"><Mail size={17}/> Get in touch</a></div><div className="metrics"><div><b>150+</b><span>LeetCode problems</span></div><div><b>3</b><span>Featured projects</span></div><div><b>2027</b><span>B.Tech graduation</span></div></div></motion.div></section>
<section id="about" className="section"><motion.div {...reveal}><p className="label">01 / ABOUT</p><div className="split"><h2>Engineering with<br/>depth & purpose.</h2><div><p className="copy">I’m Umar Farooque, a Computer Science undergraduate at AllenHouse Institute of Technology. I enjoy building software where algorithms, backend engineering and real-world reliability meet.</p><p className="copy muted">My work spans asynchronous networking, REST APIs, machine learning pipelines, observability and full application lifecycles.</p><div className="iconrow"><Code2/><Server/><Database/><BrainCircuit/></div></div></div></motion.div></section>
<section id="projects" className="section"><motion.div {...reveal}><p className="label">02 / SELECTED WORK</p><h2>Projects built to solve,<br/><span>not just showcase.</span></h2></motion.div><div className="projects">{projects.map((p,i)=><motion.article {...reveal} className={i===0?'project featured':'project'} key={p.title}><div className="projectTop"><span>{p.tag}</span><span>0{i+1}</span></div><h3>{p.title}</h3><p>{p.desc}</p><div className="chips">{p.stack.map(s=><em key={s}>{s}</em>)}</div><ul>{p.points.map(x=><li key={x}>{x}</li>)}</ul></motion.article>)}</div></section>
<section id="skills" className="section"><motion.div {...reveal}><p className="label">03 / TOOLKIT</p><div className="split"><h2>Technologies I<br/><span>work with.</span></h2><div className="skillgrid">{Object.entries(skills).map(([k,v])=><div className="skill" key={k}><h4>{k}</h4><p>{v.join(' · ')}</p></div>)}</div></div></motion.div></section>
<section className="section education"><motion.div {...reveal}><p className="label">04 / EDUCATION & TRAINING</p><div className="edu"><div><span>2023 — 2027</span><h3>B.Tech · Computer Science</h3><p>AllenHouse Institute of Technology, Kanpur · CGPA 7.2</p></div><div><span>TRAINING</span><h3>Continuous learning</h3><p>Java — Scaler · Python — Udemy · Data Structures & Algorithms — AllenHouse Institute of Technology</p></div></div></motion.div></section>
<section id="contact" className="contact"><motion.div {...reveal}><p className="label">05 / CONTACT</p><h2>Have an opportunity<br/>worth building?</h2><p>I'm interested in software development and backend engineering opportunities where I can learn fast and contribute to real products.</p><a className="primary" href="mailto:umar80643@gmail.com">umar80643@gmail.com <ArrowUpRight size={17}/></a></motion.div></section>
<footer><span>© 2026 Umar Farooque</span><span>Built with Next.js · TypeScript · Framer Motion</span></footer></main>}
